import type { Metadata } from "next";
import { Barlow_Condensed } from 'next/font/google';
import "./globals.css";
import ResponsiveNav from "./components/Navigation/ResponsiveNav";
import Footer from "./components/footer/footer";

const barlowCondensed = Barlow_Condensed({
  weight: ['300', '400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Burger | A Healthy food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowCondensed.className} antialiased`}>
        <ResponsiveNav />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
